### ISSUE TITLE
running gdeploy notifications slack test should fail if the CloudFormation stack hasn't been updated

### ISSUE THREAD

**Issue by ellie-narducci** [common-fate/glide#86]
UDE = edge case exists where `gdeploy slack notifications test` works even though `gdeploy update` hasn't yet been run

**Comment by JoshuaWilkes** [comment]
Maybe more generally, we have a warning displayed on all commands when there are changed waiting to be deployed.

The purpose of the Slack test command was to test that credentials worked. But we have since implemented an automated test for the credentials which covers this.

I think that when running the `gdeply status` or any other command it shoudl say `Warn: You have changes in your configuration which have not yet been deployed. Run 'gdeploy update' to update your deployment.

**Comment by JoshuaWilkes** [comment]
Or, we can actually add this as an "after" action which run after each command. then every command would have the same message when changes are detected
